#%RAML 1.0 Trait
queryParameters:
      page:
       type: integer
       minimum: 1
       required: false
       default: 1
      pageSize:
       type: integer
       minimum: 10
       default: 10
       required: false